### ISSUE TITLE
Unknown

### ISSUE THREAD

**Issue by TBNRItzDoge25** [BajanVlogs/AuctionHouseUI#2]
05.12 20:18:06 [Server] Server thread/INFO Enabling AuctionUI v0.0.1
05.12 20:18:06 [Server] Server thread/CRITICAL Exception: "Unable to open database: unable to open database file" (EXCEPTION) in "AuctionHouseUI_dev-9.phar/src/BajanVlogs/AuctionUI/Main" at line 42
05.12 20:18:06 [Server] Server thread/DEBUG #0 AuctionHouseUI_dev-9.phar/src/BajanVlogs/AuctionUI/Main(42): SQLite3->__construct(string /plugins/AuctionUI/AH.db)
05.12 20:18:06 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/PluginBase(90): BajanVlogs\AuctionUI\Main->onEnable()
05.12 20:18:06 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PharPluginLoader(122): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
05.12 20:18:06 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(610): pocketmine\plugin\PharPluginLoader->enablePlugin(BajanVlogs\AuctionUI\Main object)
05.12 20:18:06 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1953): pocketmine\plugin\PluginManager->enablePlugin(BajanVlogs\AuctionUI\Main object)
05.12 20:18:06 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1939): pocketmine\Server->enablePlugin(BajanVlogs\AuctionUI\Main object)
05.12 20:18:06 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1733): pocketmine\Server->enablePlugins(integer 1)
05.12 20:18:06 [Server] Server thread/DEBUG #7 src/pocketmine/PocketMine(552): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///custom-php7.2.phar/, string /, string /plugins/)
05.12 20:18:06 [Server] Server thread/DEBUG #8 /custom-php7.2.phar(1): require_once(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php 

getting this error in console

**Comment by TBNRItzDoge25** [comment]
@bajanvlogs I’m running dev build of pmmp

**Comment by TBNRItzDoge25** [comment]
forms api branch

**Comment by BajanVlogs** [comment]
Don't use formsapi
Also having other Ui plugins will cause this plugin to not work

**Comment by BajanVlogs** [comment]
Also make sure you refresh your AH.db
